language: node_js
os: linux
node_js:
  - "14"
install:
  - npm i
script:
  - npm run build
deploy:
  provider:  pages,
  cleanup: true
  local_dir: dist
  token: ${GH_TOKEN}
  keep_history: true
  on:
    branch: main
