language: node_js
os: linux
node_js: "14"
install:
  - npm i
script:
  - npm run build
after_script:
  - git clone git@github.com:daiwanxing/mlog.git .temp
  - cd .temp
  - git checkout gh-pages
  - cd ../
  - mv .temp/.git dist
  - cd dist
  - git config user.name "daiwanxing"
  - git config user.email "377099119@qq.com"
  - git add .
  - git commit -m ":construction_worker:- Build & Deploy by Travis CI"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
# E: Build LifeCycle

# 只有指定的分支提交时才会运行脚本
branches:
  only:
    - main
