language: node_js
node_js:
  - "14"
install:
  - npm i
script:
  - npm run build
delpoy:
  provider:  pages,
  skip_cleanup: true
  local_dir: dist
  github_token: ${GH_TOKEN}
  keep_history: true
  on:
    branch: gh-pages
